### ISSUE TITLE
How to resolve issue setCaptureSize() called in wrong state: 2?

### ISSUE THREAD

**Issue by ntkarale** [GautamChibde/android-audio-visualizer#23]
Dear All,

I am doing music app, it is working fine when music play first time & linearbarvisualizer set media sessionid. I switch to another activity, music play in background & come to main activity linearbarvisualizer not showing. And i set media sessionid which is stored in sharedpreference,  the error comes

Application crash & get error

<Caused by java.lang.IllegalStateException: setCaptureSize() called in wrong state: 2>

I have set linearbarvisualize enabled false but still get issue.

**Comment by vaibhav0786** [comment]
i also get the same issue

**Comment by GautamChibde** [comment]
#12 update to v2.2.0
