### ISSUE TITLE
can i user visualizer effect while i am recording audio 

### ISSUE THREAD

**Issue by mehulTank** [GautamChibde/android-audio-visualizer#24]
i want to visualizer effect while recording audio is it possible or any other method that allow set dummy animation like that if any possibly then let me know thanks in advance

**Comment by izyuroff** [comment]
See here https://github.com/GautamChibde/android-audio-visualizer/issues/2#issuecomment-347526392

**Comment by vaibhav0786** [comment]
I tried a lot while recording to add visulizer but not works and ended up by applying a same gif there
