### ISSUE TITLE
Cannot Initialize Visualizer Engine

### ISSUE THREAD

**Issue by jefry06** [GautamChibde/android-audio-visualizer#4]
Hi,

I followed the Wiki, but I still got this error.

`Caused by: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3 at android.media.audiofx.Visualizer.<init>(Visualizer.java:218)`

**Comment by GautamChibde** [comment]
@jefry06 Use of the visualizer requires the permission **android.permission.RECORD_AUDIO** so make sure to add it to your manifest file.

If you are using the device with Marshmallow or higher you need to request permission at runtime please follow [this](https://stackoverflow.com/a/34722591/5164673).

**Comment by jefry06** [comment]
Cool!. it works now. many thanks.
