### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Cannot initialize Visualizer engine, error: -3

### ISSUE THREAD

**Issue by parthitechnotion** [GautamChibde/android-audio-visualizer#40]
I have implemented this visualizer in my media player app, sometimes I am getting error like this.
Fatal Exception: java.lang.RuntimeException
Cannot initialize Visualizer engine, error: -3
Can you please let me know reason for this error and how to resolve it?

**Comment by GautamChibde** [comment]
refer #4
