### ISSUE TITLE
class path should be com.chibde.visualizer.LineBarVisualizer

### ISSUE THREAD

**Issue by NLLAPPS** [GautamChibde/android-audio-visualizer#6]
instead of com.chibde.audiovisulaizer.visualizer.LineBarVisualizer

**Comment by oluwabajio** [comment]
Please you should fix this classpath ish. i spent a lot of time trying to figure it out before i came across the solution on stackoverflow.

**Comment by drellert** [comment]
> Please you should fix this classpath ish. i spent a lot of time trying to figure it out before i came across the solution on stackoverflow.

How did you fix the classpath manually? I can't seem to find a solution on stackoverflow

**Comment by oluwabajio** [comment]
use com.chibde.visualizer.LineBarVisualizer
