### ISSUE TITLE
Provide ma method to clear the Visualizer

### ISSUE THREAD

**Issue by NLLAPPS** [GautamChibde/android-audio-visualizer#7]
It would be nice to have a method to clear artifacts from the Visualizer.
This might be used in stations where you might use the android-audio-visualizer layout again in the same activity

**Comment by GautamChibde** [comment]
check with version 2.2.0

**Comment by n9lvc5** [comment]
```
 try { lineVisualizer.release() }
        catch (e : Exception) { Log.i("Visualier","*** None present to release" ) }
```
