### ISSUE TITLE
Got it working in a service

### ISSUE THREAD

**Issue by rivercat68** [GautamChibde/android-audio-visualizer#8]
Hi I don't know if it is the correct way but I have the "line visualizer" working with a service. It does leave a line where the visualizer is located on the MainActivity when service is stopped. The line remains when a new animation starts. I will post the fix for that when I get it sorted.

1. Create new java class
`` public class Delegate {
    static MainActivity theMainActivity;
}
``
Then add this to your main activity in  onCreate
`Delegate.theMainActivity = this;
`
Finally add the visualizer code to your service
`    public int onStartCommand(Intent intent, int flags, int startId) {
       
        ///////////
        LineVisualizer lineVisualizer = Delegate.theMainActivity.findViewById(R.id.visualizer);
        lineVisualizer.clearAnimation();
        lineVisualizer.setColor(ContextCompat.getColor(this, R.color.green));
        lineVisualizer.setStrokeWidth(1);
        lineVisualizer.clearAnimation();
        ///////////////

        String stUrl = intent.getStringExtra("URL");
        Uri uri =  Uri.parse( stUrl );

        player = MediaPlayer.create(this, uri);
        player.start();
        
        /////
        lineVisualizer.setPlayer(player);
        /////
        return Service.START_STICKY;
    }`

**Comment by GautamChibde** [comment]
see issue #5
